<?php
session_start(); require_once __DIR__ . '/fun/db_connection.php';
if (!isset($_SESSION['user_id']) || !in_array($_SESSION['role'] ?? '', ['admin','vendor'], true)) { header('Location: account/login.php'); exit; }
function h($v){ return htmlspecialchars((string)$v, ENT_QUOTES, 'UTF-8'); }
$role=$_SESSION['role']; $uid=(int)$_SESSION['user_id'];
include __DIR__.'/includes/header.php'; include __DIR__.'/includes/sidebar.php';
?>
<div id="content-wrapper" class="d-flex flex-column"><div id="content"><?php include __DIR__.'/includes/topbar.php'; ?><div class="container-fluid py-4">
<style>.sm-panel{background:#fff;border-radius:12px;padding:22px;box-shadow:0 2px 14px #0000000b}.sm-table{width:100%;border-collapse:collapse}.sm-table th,.sm-table td{padding:11px;border-bottom:1px solid #eee;text-align:left}.sm-table th{background:#f8f9fc}.sm-btn{border:0;border-radius:6px;padding:7px 12px;background:#6c5ce7;color:white}.sm-field{padding:9px;border:1px solid #ddd;border-radius:6px;margin:4px;max-width:100%}</style>
<?php if($role!=='admin'){http_response_code(403);exit('Forbidden');} $msg=''; if($_SERVER['REQUEST_METHOD']==='POST' && isset($_POST['delete_id'])){$id=(int)$_POST['delete_id'];$s=mysqli_prepare($conn,'DELETE FROM products WHERE id=?');mysqli_stmt_bind_param($s,'i',$id);mysqli_stmt_execute($s);$msg='تم حذف المنتج إن لم يكن مرتبطًا بطلبات.';} $r=mysqli_query($conn,"SELECT p.id,p.name,p.price,p.category,u.Name vendor FROM products p LEFT JOIN users u ON u.id=p.vendor_id ORDER BY p.id DESC"); ?><h1 class="h3 mb-4">Products Management</h1><div class="sm-panel"><?php if($msg)echo '<p>'.h($msg).'</p>'; ?><div class="table-responsive"><table class="sm-table"><tr><th>ID</th><th>Product</th><th>Vendor</th><th>Category</th><th>Price</th><th></th></tr><?php while($p=mysqli_fetch_assoc($r)): ?><tr><td><?=h($p['id'])?></td><td><?=h($p['name'])?></td><td><?=h($p['vendor'])?></td><td><?=h($p['category'])?></td><td><?=h($p['price'])?></td><td><form method="post" onsubmit="return confirm('Delete this product?')"><input type="hidden" name="delete_id" value="<?=h($p['id'])?>"><button class="sm-btn" type="submit">Delete</button></form></td></tr><?php endwhile; ?></table></div></div></div></div><?php include __DIR__.'/includes/footer.php'; ?></div>